# Generated by Django 4.1.5 on 2023-02-05 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='category_product', to='category.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='prodcut_status',
            field=models.CharField(choices=[('На модерации', 'На модерации'), ('Активный', 'Активный'), ('Не активный', 'Не активный'), ('Откланён', 'Откланён')], default='На модерации', max_length=25),
        ),
    ]
