# Generated by Django 4.1.5 on 2023-02-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_about_self'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseted_passwords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=15)),
            ],
        ),
    ]
